apiVersion: v1
appVersion: "333"
description: Distributed SQL query engine for running interactive analytic queries
home: https://prestosql.io
icon: https://prestosql.io/static/presto.png
maintainers:
- email: pavan4devops@gmail.com
  name: pavan
name: presto
sources:
- https://github.com/facebook/presto
version: 0.1.0