apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: prestos.abc.com
spec:
  group: abc.com
  names:
    kind: Presto
    listKind: PrestoList
    plural: prestos
    singular: presto
  scope: Namespaced
  subresources:
    status: {}
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
