kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: presto-operator
rules:
- apiGroups:
  - autoscaling
  resources:
    - horizontalpodautoscalers
  verbs:
    - '*'
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - '*'
- apiGroups:
  - networking.k8s.io
  resources:
  - networkpolicies
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - '*'
- apiGroups:
  - abc.com
  resources:
  - '*'
  verbs:
  - '*'
