apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "presto.coordinator" . }}
  namespace: {{ .Values.server.namespace }}
  labels:
    app: presto
    presto: coordinator
    chart: {{ template "presto.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: presto-coordinator
spec:
  selector:
    matchLabels:
      app: presto
      presto: coordinator
      release: {{ .Release.Name }}
      component: presto-coordinator
  template:
    metadata:
      labels:
        app: presto
        presto: coordinator
        release: {{ .Release.Name }}
        component: presto-coordinator
    spec:
      volumes:
        - name: config-volume
          configMap:
            name: {{ template "presto.coordinator" . }}
        - name: catalog-volume
          configMap:
            name: {{ template "presto.catalog" . }}
      terminationGracePeriodSeconds: 5
      containers:
        - name: {{ .Chart.Name }}-coordinator
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/bin/bash"]
          args:
            - {{ .Values.server.config.path }}/docker-presto.sh
          volumeMounts:
            - mountPath: {{ .Values.server.config.path }}
              name: config-volume
            - mountPath: {{ .Values.server.config.path }}/catalog
              name: catalog-volume
          ports:
            - name: http-coord
              containerPort: {{ .Values.server.config.http.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /v1/cluster
              port: http-coord
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /v1/cluster
              port: http-coord
            initialDelaySeconds: 5
            periodSeconds: 2
            failureThreshold: 30
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
