{{- if gt (int .Values.server.workers) 0 }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "presto.worker" . }}
  namespace: {{ .Values.server.namespace }}
  labels:
    app: presto
    presto: coordinator
    chart: {{ template "presto.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: presto-worker
  annotations:
    autoScale.enabled: "{{ .Values.server.autoscale.enabled }}"
    autoScale.expectedQueriesPerWorker: "{{ .Values.server.autoscale.expectedQueriesPerWorker }}"
    autoScale.minWorkers: "{{ .Values.server.autoscale.minWorkers }}"
    autoScale.maxWorkers: "{{ .Values.server.autoscale.maxWorkers }}"
    autoScale.coolDownDelayInSecs: "{{ .Values.server.autoscale.coolDownDelayInSecs }}"
spec:
  replicas: {{ .Values.server.workers }}
  selector:
    matchLabels:
      app: presto
      presto: coordinator
      release: {{ .Release.Name }}
      component: presto-worker
  template:
    metadata:
      labels:
        app: presto
        presto: coordinator
        release: {{ .Release.Name }}
        component: presto-worker
    spec:
      volumes:
        - name: config-volume
          configMap:
            name: {{ template "presto.worker" . }}
        - name: catalog-volume
          configMap:
            name: {{ template "presto.catalog" . }}
      terminationGracePeriodSeconds: 5
      containers:
        - name: {{ .Chart.Name }}-worker
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/bin/bash"]
          args:
            - {{ .Values.server.config.path }}/docker-presto.sh
          volumeMounts:
            - mountPath: {{ .Values.server.config.path }}
              name: config-volume
            - mountPath: {{ .Values.server.config.path }}/catalog
              name: catalog-volume
          ports:
            - name: http-coord
              containerPort: {{ .Values.server.config.http.port }}
              protocol: TCP
          livenessProbe:
            exec:
              command:
                - /bin/bash
                - {{ .Values.server.config.path }}/health_check.sh
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 10
          readinessProbe:
            exec:
              command:
                - /bin/bash
                - {{ .Values.server.config.path }}/health_check.sh
            initialDelaySeconds: 12
            periodSeconds: 2
            failureThreshold: 30
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}

{{- end }}